apiVersion: batch/v1
kind: Job
metadata:
  name: caption-worker-job
  labels:
    app.kubernetes.io/instance: caption-worker-dev 
    app.kubernetes.io/part-of: stress-app
    app.kubernetes.io/managed-by: kustomize
spec:
  template:
    metadata:
      name: caption-worker 
      labels:
        app.kubernetes.io/name: caption-worker
        
    spec: 
      containers:
        - name: caption-worker 
          image: "533267453751.dkr.ecr.us-east-1.amazonaws.com/caption_worker:latest"
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"         # Minimum CPU guaranteed
              memory: "128Mi"     # Minimum memory guaranteed
            limits:
              cpu: "200m"         # Max CPU allowed
              memory: "256Mi"     # Max memory allowed
              
          envFrom:
            - configMapRef:
                name: caption-worker-config
            - secretRef:
                name: caption-worker-secret 
      serviceAccountName: caption-sa  
      restartPolicy: OnFailure
