apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - secret.yaml

namespace: dev 

commonLabels:
  app.kubernetes.io/name: caption-worker
  app.kubernetes.io/component: backend