apiVersion: v1
kind: Secret
metadata:
  name: caption-worker-secret

data:
  REDIS_HOST: 
  REDIS_PORT: 
  REDIS_DB: 
  MQ_USERNAME: 
  MQ_PASSWORD:
  MQ_BROKER_ID: 
  DEEPGRAM_API_KEY: 
  MONGO_URI: 