apiVersion: v1 
kind: ConfigMap
metadata:
  name: caption-backend-configmap
  labels:
    env: dev 
  namespace: dev 

data:
  REDIS_DB: "0" 
  RABBITMQ_QUEUE_NAME: "stress"
  MONGO_DB: "stress_app"
  MONGO_COLLECTION: "transcripts"
  LOG_DIR: "logs"