apiVersion: apps/v1 
kind: Deployment
metadata:
  name: caption-backend-deployment
  labels:
    env: dev 
    app: caption-backend
  namespace: dev 

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: caption-backend-pod
      env: dev 

  template:
    metadata: 
      name: caption-backend
      labels:
        env: dev
        app: caption-backend-pod
      namespace: dev 

    spec:
      containers: 
        - name: caption-backend-main
          image: caption-service:latest 
          imagePullPolicy: Never

          envFrom:
            - configMapRef: 
                name: caption-backend-configmap

            - secretRef:
                name: caption-backend-secret 