apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upload-backend-deployment
  namespace: dev 
  labels:
    env: dev 
    app: upload-backend
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev 
      app: upload-backend
  template:
    metadata:
      name: upload-backend-pod 
      labels:
        env: dev 
        app: upload-backend
      namespace: dev 
    spec: 
      containers:
        - name: upload-backend-main 
          image: upload-service:latest
          imagePullPolicy: Never 
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: upload-backend-secret
                  key: AUTH_SERVICE

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: upload-backend-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: upload-backend-secret
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: upload-backend-secret
                  key: REDIS_PORT

            - name: OBJECT_STORE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: upload-backend-configmap
                  key: OBJECT_STORE_BUCKET_NAME
            
            - name: RABBITMQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_QUEUE_NAME
                  name: upload-backend-configmap

            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: upload-backend-configmap
                  key: S3_REGION

            - name: PRESIGNED_URL_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: upload-backend-configmap
                  key: PRESIGNED_URL_EXPIRATION

            - name: LOG_DIR
              valueFrom:  
                configMapKeyRef:
                  name: upload-backend-configmap
                  key: LOG_DIR

      restartPolicy: Always 