apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app.kubernetes.io/instance: upload-service-dev 
    app.kubernetes.io/part-of: stress-app 
    app.kubernetes.io/managed-by: kustomize
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: upload-service 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: upload-service 
    spec: 
      containers:
        - name: upload
          image: "533267453751.dkr.ecr.us-east-1.amazonaws.com/upload_service:latest"
          imagePullPolicy: Always 

          resources:
            requests:
              cpu: "100m"         # Minimum CPU guaranteed
              memory: "128Mi"     # Minimum memory guaranteed
            limits:
              cpu: "200m"         # Max CPU allowed
              memory: "256Mi"     # Max memory allowed
          
          envFrom:
            - configMapRef:
                name: upload-config 
            
            - secretRef:
                name: upload-secret 

      serviceAccountName: upload-sa
      restartPolicy: Always 