apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app.kubernetes.io/instance: upload-service-dev 
    app.kubernetes.io/part-of: stress-app 
    app.kubernetes.io/managed-by: kustomize
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: upload-service 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: upload-service 
    spec: 
      containers:
        - name: upload
          image: "533267453751.dkr.ecr.us-east-1.amazonaws.com/upload_service:latest"
          imagePullPolicy: Always 
          
          envFrom:
            - configMapRef:
                name: upload-config 
            
            - secretRef:
                name: upload-secret 

      serviceAccountName: upload-sa
                
      restartPolicy: Always 