apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app.kubernetes.io/instance: upload-service-dev 
    app.kubernetes.io/part-of: stress-app 
    app.kubernetes.io/managed-by: kustomize
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: upload-service 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: upload-service 
    spec: 
      containers:
        - name: upload
          image: ""
          imagePullPolicy: Always 
          
          envFrom:
            - configMapRef:
                name: upload-config 
            
            - secretRef:
                name: upload-secret 

      serviceAccountName: upload-sa
                
      restartPolicy: Always 