apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secret.yaml
  - service.yaml
  - configmap.yaml

namespace: dev 

commonLabels:
  app.kubernetes.io/name: upload-service 
  app.kubernetes.io/component: backend 