apiVersion: v1 
kind: Service 
metadata: 
  name: upload-service 
 
spec:
  type: ClusterIP 
  selector:
    app.kubernetes.io/name: upload-service
  ports:
    - name: main 
      port: 8002
      targetPort: 8002