apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: caption-worker-scaler

spec:
  scaleTargetRef:
    name: caption-worker
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10

  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: RABBITMQ_HOST
        queueName: stress 
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: rabbitmq-auth
