apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: default

spec:
  secretTargetRef:
    - parameter: host
      name: caption-worker-keda-secret
      key: RABBITMQ_HOST
