apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev 

resources:
  - keda-authn.yaml 
  - secret.yaml 
  - keda.yaml 

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: scaler
      app.kubernetes.io/name: metric-server-cpa