apiVersion: v1
kind: Secret
metadata:
  name: auth-secret

data:
  DB_HOST: 
  DB_PORT: "MzMwNg=="
  DB_USER: "YWRtaW4="
  DB_PASS: 
  DB_NAME: "c3RyZXNz"
  JWT_ACCESS_SECRET_KEY: "c2hpbHU="
  JWT_REFRESH_SECRET_KEY: "c2hpbHU="
