apiVersion: v1
kind: Secret
metadata:
  name: auth-secret

data:
  DB_HOST: dXBsb2FkLXNlcnZpY2UtZGIuYzdzcTh3eTh5bHJmLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_PORT: "MzMwNg=="
  DB_USER: "YWRtaW4="
  DB_PASS: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
  DB_NAME: "c3RyZXNz"
  JWT_ACCESS_SECRET_KEY: "c2hpbHU="
  JWT_REFRESH_SECRET_KEY: "c2hpbHU="
