apiVersion: v1 
kind: Secret 
metadata: 
  name: auth-secret 

data:
  DB_HOST: "=="
  DB_PORT: "=="
  DB_USER: "="
  DB_PASS: "=" 
  DB_NAME: "" 
  JWT_ACCESS_SECRET_KEY: "="
  JWT_REFRESH_SECRET_KEY: "="
