apiVersion: v1 
kind: Service 
metadata:
  name: auth-service 

spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: auth-service
  ports:
    - name: flask-app
      port: 8001
      targetPort: 8001