apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../infra-definitions/auth-service/base/
- hpa.yaml
patches:
- path: patch-resources.yaml
  target:
    group: apps
    kind: Deployment
    name: auth-deployment
    version: v1
namespace: dev
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: auth-service
