apiVersion: v1 
kind: ConfigMap 
metadata:
  name: stress-config
    
data:
  NAMESPACE: "dev"
  LABEL_SELECTOR: "app.kubernetes.io/name=auth-service"
  ENDPOINT: "auth-service.dev.svc.cluster.local"
  PORT: "8001"
  LOAD: "85"
  VM_WORKERS: "1"
  DURATION: "60"
  WORKERS: "1"
  STRESS_TYPE: "cpu"
  MEM_BYTES: "10"