apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
  namespace: dev
  labels:
    app.kubernetes.io/instance: stress-dev
    app.kubernetes.io/part-of: stress-app
    app.kubernetes.io/managed-by: kustomize

spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress
    spec:
      containers:
        - name: stress
          image: 533267453751.dkr.ecr.us-east-1.amazonaws.com/stress_app:latest
          envFrom:
            - configMapRef:
                name: stress-config

      serviceAccountName: stress-sa
      restartPolicy: OnFailure
