apiVersion: batch/v1 
kind: Job
metadata:
  name: stress-job
  labels:
    app.kubernetes.io/instance: stress-dev 
    app.kubernetes.io/part-of: stress-app 
    app.kubernetes.io/managed-by: kustomize

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stress
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: stress

    spec:
      containers: 
        - name: stress
          image: stress-app:latest 
          imagePullPolicy: Never 
          
          envFrom:
            configMapRef:
              name: stress-config