apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- configmap.yaml
- job.yaml
- role.yaml
- rolebinding.yaml
- service-account.yaml
namespace: dev
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: stress-job


