apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources: 
  - configmap.yaml
  - job.yaml 

namespace: dev 
commonLabels:
  app.kubernetes.io/name: stress-job
  app.kubernetes.io/component: backend 