apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stress-pod-reader-binding
  namespace: dev
  
subjects:
  - kind: ServiceAccount
    name: stress-sa  # or better: create a custom SA and use that in your deployment
    namespace: dev

roleRef:
  kind: Role
  name: stress-pod-reader
  apiGroup: rbac.authorization.k8s.io
