apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: main-app-role
  labels:
    env: dev
    app: main-app
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "deployments", "service"]
    verbs: ["get", "watch", "list"]