apiVersion: v1
kind: Service
metadata:
  name: main-app-service
  labels:
    env: dev
spec:
  type: ClusterIP
  selector:
    env: dev
    app: backend
  ports:
    - name: backend-port
      port: 8000