apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gateway-backend-deployment
  namespace: dev 
  labels:
    env: dev 
    app: gateway-backend
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev 
      app: gateway-backend
  template:
    metadata:
      name: gateway-backend-pod 
      labels:
        env: dev 
        app: gateway-backend
      namespace: dev 
    spec: 
      containers:
        - name: gateway-backend-main 
          image: gateway-service:latest
          imagePullPolicy: Never 
          env:
            - name: AUTH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-backend-configmap
                  key: AUTH_SERVICE

            - name: UPLOAD_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-backend-configmap
                  key: UPLOAD_SERVICE

            - name: CAPTION_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-backend-configmap
                  key: CAPTION_SERVICE

            - name: AUTH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-backend-configmap
                  key: AUTH_SERVICE_PORT

            - name: UPLOAD_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-backend-configmap
                  key: UPLOAD_SERVICE_PORT
            
            - name: CAPTION_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: CAPTION_SERVICE_PORT
                  name: gateway-backend-configmap

      restartPolicy: Always 