apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gateway-backend-deployment
  namespace: dev 
  labels:
    env: dev 
    app: gateway-backend
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev 
      app: gateway-backend
  template:
    metadata:
      name: gateway-backend-pod 
      labels:
        env: dev 
        app: gateway-backend
      namespace: dev 
    spec: 
      containers:
        - name: gateway-backend-main 
          image: gateway-service:latest
          imagePullPolicy: Never 
          
          envFrom:
            - configMapRef: 
                name: gateway-backend-configmap

            - secretRef:
                name: gateway-backend-secret
              
      restartPolicy: Always 