apiVersion: v1 
kind: Service 
metadata:
  name: gateway-backend
  namespace: dev 
  labels: 
    env: dev 
    app: gateway-backend 
spec:
  type: ClusterIP 
  selector:
    env: dev 
    app: gateway-backend
  ports:
    - name: main 
      port: 8000
      targetPort: 8000