apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../infra-definitions/auth-service/base/
  - hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: auth-service

