apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: root-and-shilash-cluster-admin-binding
subjects:
- kind: User
  name: root
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: shilash
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

