apiVersion: v1 
kind: Service 
metadata:
  name: auth-backend-service 
  labels:
    env: dev 
    app: auth-backend-service 
  namespace: dev 

spec:
  type: ClusterIP
  selector: 
    env: dev 
    app: auth-backend-service
  ports:
    - name: flask-app
      port: 8001
      targetPort: 8001