apiVersion: apps/v1 
kind: Deployment
metadata:
  name: caption-deployment
  labels:
    app.kubernetes.io/instance: caption-service-dev
    app.kubernetes.io/part-of: stress-app 
    app.kubernetes.io/managed-by: kustomize

spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: caption-service
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: caption-service
    spec:
      containers: 
        - name: caption
          image: "533267453751.dkr.ecr.us-east-1.amazonaws.com/caption_service:latest"
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"         # Minimum CPU guaranteed
              memory: "128Mi"     # Minimum memory guaranteed
              
            limits:
              cpu: "200m"         # Max CPU allowed
              memory: "256Mi"     # Max memory allowed

          envFrom:
            - configMapRef: 
                name: caption-config

            - secretRef:
                name: caption-secret