apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - configmap.yaml

commonLabels: 
  app.kubernetes.io/name: caption-service 
  app.kubernetes.io/compoenent: backend 

namespace: dev