apiVersion: v1 
kind: Service 
metadata:
  name: caption-service

spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: caption-service
  ports:
    - name: main 
      port: 5000
      targetPort: 5000