apiVersion: apps/v1 
kind: Deployment
metadata:
  name: caption-worker
  namespace: dev 
  labels:
    env: dev 
    app: caption-worker
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev 
      app: caption-worker
  template:
    metadata:
      name: caption-worker 
      labels:
        env: dev 
        app: caption-worker
      namespace: dev 
    spec: 
      containers:
        - name: caption-worker 
          image: caption-worker:latest
          imagePullPolicy: Never 
          
          envFrom:
            - configMapRef:
                name: caption-worker-configmap

            - secretRef:
                name: caption-worker-secret 
              
      restartPolicy: Always 