apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - t3.medium
        - t3.large
        - t3a.medium
        - t3a.large
        - m5.large
        - m5a.large
        - c5.large
        - c5a.large
        - r5.large
        - r5a.large
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: stress-app-cluster
    securityGroupSelector:
      karpenter.sh/discovery: stress-app-cluster
  ttlSecondsAfterEmpty: 30
