apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: gateway-service
  labels:
    env: dev 
spec:
  selector:
    matchLabels:
      env: dev
      app: gateway-service

  replica: 2
  template:
    metadata:
      env: dev 
      app: gateway-service
    spec:
      containers:
        - name: gateway-app 
          image: stress-gateway-service:latest
          imagePullPolicy: Always

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000

            initialDelaySeconds: 3
            periodSeconds: 3

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000

            failureThreshold: 30
            periodSeconds: 10

        
      restartPolicy: Always