apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: gateway-service
  labels:
    env: dev
spec:
  type: ClusterIP
  selector:
    env: dev
    app: gateway-service
  ports:
    - name: backend-port
      port: 8000