apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../infra-definitions/auth-service/base/
  - hpa.yaml

replicas:
  - name: auth-deployment
    count: 1

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: auth-service

configMapGenerator:
  - name: auth-cpu-and-mem-stress-config
    literals:
      - NAMESPACE="dev"
      - LABEL_SELECTOR="app.kubernetes.io/name=auth-service"
      - ENDPOINT="auth-service.dev.svc.cluster.local"
      - PORT="8001"
      - LOAD="85"
      - VM_WORKERS="1"
      - DURATION="60"
      - WORKERS="1"
      - STRESS_TYPE="cpu_and_mem"
      - MEM_BYTES="200"