apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: dev 
  labels:
    app.kubernetes.io/instance: gateway-service-instance
    app.kubernetes.io/part-of: stress-app
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-service

    spec: 
      containers:
        - name: gateway
          image: "533267453751.dkr.ecr.us-east-1.amazonaws.com/gateway_service:latest"
          imagePullPolicy: Always 
          
          resources:
            requests:
              cpu: "100m"         # Minimum CPU guaranteed
              memory: "128Mi"     # Minimum memory guaranteed
            limits:
              cpu: "200m"         # Max CPU allowed
              memory: "256Mi"     # Max memory allowed
              
          envFrom:
            - configMapRef: 
                name: gateway-config

      restartPolicy: Always 