apiVersion: kustomize.config.k8s.io/v1
kind: kustomize

resources:
  - deployment.yaml
  - secret.yaml 
  - service.yaml 
  - configmap.yaml 

namespace: dev 

commonLabels:
  app.kubernetes.io/name: gateway-service 
  app.kubernetes.io/compoenent: backend 
