apiVersion: v1 
kind: Service 
metadata:
  name: gateway-service
    
spec:
  type: ClusterIP 
  selector:
    app.kubernetes.io/name: gateway-service
  ports:
    - name: main 
      port: 8000
      targetPort: 8000