apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      env: dev
      app: backend
  replicas: 2
  template:
    metadata:
      name: main-app-pod
      labels:
        env: dev
        app: backend
    spec:
      containers:
        - name: main-app-container
          image: 18bit048/scaler-app:v4
          imagePullPolicy: Always
      serviceAccountName: main-app-sa
     # imagePullSecret: docker-secret
      