apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-proportional-autoscaler-metrics-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpa-metrics
  template:
    metadata:
      labels:
        app: cpa-metrics
    spec:
      containers:
      - name: autoscaler
        image: registry.k8s.io/cpa/cluster-proportional-autoscaler:1.8.5
        command:
        - /cluster-proportional-autoscaler
        - --namespace=kube-system
        - --configmap=metrics-server-autoscaler
        - --target=Deployment/metrics-server
        - --logtostderr=true
        - --v=2
