apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-proportional-autoscaler

rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update", "patch"]
