apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-proportional-autoscaler
  
subjects:
- kind: ServiceAccount
  name: cpa-metrics
  namespace: kube-system
  
roleRef:
  kind: Role
  name: cluster-proportional-autoscaler
  apiGroup: rbac.authorization.k8s.io
