apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: upload-service-cpu-and-mem 

spec:
  targetRef:                # REQUIRED
    apiVersion: apps/v1     # Should match your workload type
    kind: Deployment
    name: upload-deployment

  updatePolicy:
    updateMode: "Auto"      # Off | Initial | Auto

  resourcePolicy:           # (Optional) Per-container rules
    containerPolicies:
      - containerName: "*"  # "*" applies to all containers
        minAllowed:
          cpu: "100m"
          memory: "100Mi"
          
        maxAllowed:
          cpu: "1000m"
          memory: "512Mi"
        controlledResources: ["cpu", "memory"]  # or leave empty for all
