apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: caption-worker-vpa-cpu

spec:
  targetRef:                # REQUIRED
    apiVersion: apps/v1     # Should match your workload type
    kind: Job
    name: caption-job

  updatePolicy:
    updateMode: "Auto"      # Off | Initial | Auto

  resourcePolicy:           # (Optional) Per-container rules
    containerPolicies:
      - containerName: "*"  # "*" applies to all containers
        minAllowed:
          cpu: "100m"
          
        maxAllowed:
          cpu: "1000m"
        controlledResources: ["cpu"]  # or leave empty for all
