apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../infra-definitions/upload-service/base/
  - ../../../../infra-definitions/stress-app/base/
  - hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: upload-service

configMapGenerator:
  - name: upload-stress-cpu-and-mem-config
    literals:
      - NAMESPACE="dev"
      - LABEL_SELECTOR="app.kubernetes.io/name=upload-service"
      - ENDPOINT="upload-service.dev.svc.cluster.local"
      - PORT="8002"
      - LOAD="85"
      - VM_WORKERS="1"
      - DURATION="60"
      - WORKERS="1"
      - STRESS_TYPE="cpu_and_mem"
      - MEM_BYTES="250"

